import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "./components/Navbar";
import CartDrawer from "./components/CartDrawer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener('error', function(event) {
                if (event.message?.includes('chrome.runtime.sendMessage') || event.message?.includes('Extension ID')) {
                  event.stopImmediatePropagation();
                  event.preventDefault();
                  console.warn("Suppressed extension error:", event.message);
                }
              }, true);
              window.addEventListener('unhandledrejection', function(event) {
                if (event.reason?.message?.includes('chrome.runtime.sendMessage') || event.reason?.message?.includes('Extension ID')) {
                  event.stopImmediatePropagation();
                  event.preventDefault();
                  console.warn("Suppressed extension promise rejection:", event.reason);
                }
              }, true);
            `,
          }}
        />
        <Navbar />
        <CartDrawer />
        {children}
      </body>
    </html>
  );
}
